swagger: '2.0'
info:
  title: Django Generator
  description: Test description
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: contact@snippets.local
  license:
    name: BSD License
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /v1/testview/:
    get:
      operationId: TESTVIEW
      description: ''
      parameters: 
      - name: "param1"
        in: "query"
        required: true
        type: "string"
      - name: "param2"
        in: "query"
        required: true
        type: "string"
      - name: "param3"
        in: "query"
        required: true
        type: "string"
      - name: "param4"
        in: "query"
        required: false
        type: "string"
      responses:
        '200':
          description: ''
      tags:
        - test_view
    parameters: []